/**
 * Seed Knowledge Base — runtime Rules compile from these concepts (not hardcoded in engine).
 */

import type { KnowledgeConcept } from './types';

function c(input: Omit<KnowledgeConcept, 'updatedAt' | 'hitCount' | 'source' | 'enabled'> & {
  enabled?: boolean;
  hitCount?: number;
  source?: KnowledgeConcept['source'];
}): KnowledgeConcept {
  return {
    ...input,
    enabled: input.enabled !== false,
    hitCount: input.hitCount ?? 0,
    source: input.source || 'seed',
    updatedAt: new Date().toISOString(),
  };
}

export const DEFAULT_KNOWLEDGE_CONCEPTS: KnowledgeConcept[] = [
  c({
    id: 'buyer_intent',
    category: 'buyer',
    concept: 'Buyer Intent',
    aliases: [
      'cần mua',
      'muốn mua',
      'gom hàng',
      'xuống tiền',
      'tìm hàng',
      'xin hàng',
      'pass hàng',
      'săn hàng',
      'tìm mua',
      'đang tìm',
      'ai bán',
      'xin tư vấn',
      'gửi thông tin',
      'mua nhà',
      'mua đất',
    ],
    synonyms: ['khách cần', 'cần tìm nhà', 'cần tìm đất'],
    weight: 40,
    examples: ['Cần mua đất Mai Đăng Chơn', 'Muốn mua nhà Hòa Xuân'],
    negativeExamples: ['Cần bán nhà', 'Em bán đất'],
    campaignMapping: null,
    priority: 10,
  }),
  c({
    id: 'buyer_finance',
    category: 'signal',
    concept: 'Buyer Finance',
    aliases: ['tài chính', 'ngân sách', 'bao nhiêu', 'ôm tiền', 'sẵn tiền'],
    synonyms: ['có tiền', 'budget'],
    weight: 30,
    examples: ['Tài chính sẵn sàng'],
    negativeExamples: [],
    campaignMapping: null,
    priority: 15,
  }),
  c({
    id: 'seller_intent',
    category: 'seller',
    concept: 'Seller Intent',
    aliases: ['cần bán', 'ra hàng', 'thoát hàng', 'cắt lỗ', 'ký gửi', 'bán gấp', 'chính chủ', 'em bán'],
    synonyms: ['xả hàng', 'thanh lý đất'],
    weight: -60,
    examples: ['Cần bán gấp chính chủ'],
    negativeExamples: ['Cần mua đất'],
    campaignMapping: null,
    priority: 5,
  }),
  c({
    id: 'broker_intent',
    category: 'broker',
    concept: 'Broker Intent',
    aliases: ['ib em', 'zalo em', 'liên hệ em', 'e hỗ trợ'],
    synonyms: ['inbox em', 'alo em'],
    weight: -35,
    examples: ['IB em hỗ trợ'],
    negativeExamples: [],
    campaignMapping: null,
    priority: 20,
  }),
  c({
    id: 'rent_intent',
    category: 'rent',
    concept: 'Rent Intent',
    aliases: ['thuê', 'cần thuê', 'tìm thuê', 'mặt bằng', 'cho thuê'],
    synonyms: [],
    weight: -40,
    examples: ['Cần thuê mặt bằng'],
    negativeExamples: [],
    campaignMapping: null,
    priority: 12,
  }),
  c({
    id: 'spam_noise',
    category: 'spam',
    concept: 'Spam Noise',
    aliases: ['tuyển dụng', 'việc làm', 'tuyển', 'livestream', 'game', 'giveaway', 'điện thoại'],
    synonyms: ['hiring', 'job'],
    weight: -80,
    examples: ['Tuyển dụng livestream'],
    negativeExamples: [],
    campaignMapping: null,
    priority: 1,
  }),
  c({
    id: 'loc_mai_dang_chon',
    category: 'location',
    concept: 'Mai Đăng Chơn',
    aliases: ['mai đăng chơn', 'mdc', 'mai dang chon', 'maiđăngchơn'],
    synonyms: ['kđt mai đăng chơn'],
    weight: 20,
    examples: ['Đất Mai Đăng Chơn'],
    negativeExamples: [],
    campaignMapping: 'Mai Đăng Chơn',
    priority: 20,
  }),
  c({
    id: 'loc_hoa_xuan',
    category: 'location',
    concept: 'Hòa Xuân',
    aliases: ['hòa xuân', 'hoa xuan'],
    synonyms: [],
    weight: 18,
    examples: [],
    negativeExamples: [],
    campaignMapping: 'Hòa Xuân',
    priority: 21,
  }),
  c({
    id: 'loc_ngu_hanh_son',
    category: 'location',
    concept: 'Ngũ Hành Sơn',
    aliases: ['ngũ hành sơn', 'ngu hanh son'],
    synonyms: [],
    weight: 15,
    examples: [],
    negativeExamples: [],
    campaignMapping: 'Ngũ Hành Sơn',
    priority: 22,
  }),
  c({
    id: 'loc_son_tra',
    category: 'location',
    concept: 'Sơn Trà',
    aliases: ['sơn trà', 'son tra'],
    synonyms: [],
    weight: 12,
    examples: [],
    negativeExamples: [],
    campaignMapping: null,
    priority: 25,
  }),
  c({
    id: 'property_dat_nen',
    category: 'property',
    concept: 'Đất nền',
    aliases: ['đất nền', 'đất', 'lô', 'lô đất', 'đất ở'],
    synonyms: ['nền đất'],
    weight: 12,
    examples: ['Bán lô đất nền'],
    negativeExamples: [],
    campaignMapping: null,
    priority: 30,
  }),
  c({
    id: 'signal_legal',
    category: 'research',
    concept: 'Legal Signal',
    aliases: ['sổ', 'sổ đỏ', 'pháp lý'],
    synonyms: ['sổ hồng'],
    weight: 12,
    examples: [],
    negativeExamples: [],
    campaignMapping: null,
    priority: 35,
  }),
  c({
    id: 'investor_intent',
    category: 'investor',
    concept: 'Investor Intent',
    aliases: ['đầu tư', 'hàng ngộp', 'cashflow', 'dòng tiền'],
    synonyms: ['roi'],
    weight: 22,
    examples: ['Đầu tư hàng ngộp'],
    negativeExamples: [],
    campaignMapping: null,
    priority: 25,
  }),
  c({
    id: 'research_intent',
    category: 'research',
    concept: 'Research Intent',
    aliases: ['tìm hiểu', 'tham khảo'],
    synonyms: [],
    weight: 10,
    examples: [],
    negativeExamples: [],
    campaignMapping: null,
    priority: 40,
  }),
];
