import { AppSettings, ChatMessage } from '../types';

export const DEFAULT_SETTINGS: AppSettings = {
  ai_mode: 'auto',
  ollama_endpoint: 'http://localhost:11434',
  ollama_model: 'qwen3:8b',
  openai_model: 'gpt-5-mini',
  agent_tone: 'chuyên nghiệp',
  telegram_enabled: false,
  telegram_bot_token: '',
  telegram_chat_id: '',
  telegram_min_score: 70,
  telegram_classifications: ['buyer', 'renter', 'investor'],
  telegram_only_with_phone: false,
  telegram_include_phone: true,
  telegram_include_budget: true,
  telegram_include_location: true,
  telegram_include_link: true,
  telegram_quiet_hours_start: '',
  telegram_quiet_hours_end: '',
  telegram_console_enabled: false,
  telegram_console_mode: 'polling',
  telegram_allowed_user_ids: '',
  telegram_allowed_chat_ids: '',
  telegram_admin_user_ids: '',
  telegram_webhook_secret: '',
  agent_sync_enabled: false,
  agent_sync_vps_url: '',
  agent_sync_key_id: '',
  agent_sync_secret: '',
  agent_sync_company_id: '',
  agent_sync_worker_id: '',
  agent_sync_batch_size: 10,
  agent_sync_timeout_ms: 20000,
  agent_sync_verify_tls: true,
  gemini_api_key: '',
  openai_api_key: '',
  finding_ai_gate_enabled: true,
};

export const ASSISTANT_WELCOME_MESSAGE: ChatMessage = {
  role: 'model',
  content: 'Xin chào! Tôi là Trợ lý Real Estate AI Marketing Agent. Tôi nắm bắt toàn bộ danh sách khách hàng CRM và danh sách bất động sản. Bạn cần tôi trợ giúp gì hôm nay?',
  timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
};
