/**
 * Default keyword packs for Nam Đà Nẵng real-estate lead analysis.
 * Applied at resolve-time when source/mission leave keywords empty.
 * Do NOT write these into AgentSource.config automatically.
 */

export const DEFAULT_REAL_ESTATE_KEYWORDS = {
  buyer: [
    "cần mua",
    "muốn mua",
    "đang cần mua",
    "tìm mua",
    "đang tìm mua",
    "cần tìm mua",
    "cần tìm",
    "đang tìm",
    "ai có căn",
    "ai có nhà",
    "ai có đất",
    "có căn nào",
    "có nhà nào",
    "có lô nào",
    "có đất nào",
    "cần căn",
    "tìm căn",
    "tìm nhà",
    "tìm đất",
    "tìm lô",
    "mua nhà",
    "mua đất",
    "mua căn hộ",
    "mua chung cư",
    "mua shophouse",
    "mua biệt thự",
    "mua mặt bằng",
    "mua nhà phố",
    "mua đất nền",
    "mua đất mặt tiền",
    "mua quỹ đất",
    "tìm quỹ đất",
    "cần quỹ đất",
    "tìm đất lớn",
    "cần đất lớn",
    "tìm đất xây căn hộ",
    "tìm đất xây khách sạn",
    "tìm đất kinh doanh",
    "tìm đất làm căn hộ",
    "tìm đất làm homestay",
    "tìm đất làm showroom",
    "tìm đất làm văn phòng",
    "tìm mặt bằng mua",
    "mua để ở",
    "mua ở",
    "mua đầu tư",
    "mua khai thác",
    "mua giữ tiền",
    "mua dòng tiền",
    "chốt nhanh",
    "mua nhanh",
    "cần gấp",
    "ưu tiên chính chủ",
    "ưu tiên giá tốt",
    "ưu tiên pháp lý rõ ràng",
    "ưu tiên sổ đỏ",
    "ưu tiên đường lớn",
    "ưu tiên ô tô vào",
    "ưu tiên mặt tiền",
    "ưu tiên gần biển",
    "ưu tiên gần fpt",
    "ưu tiên nam đà nẵng"
  ],
  investor: [
    "tìm cơ hội đầu tư",
    "cần đầu tư",
    "muốn đầu tư",
    "đang tìm kênh đầu tư",
    "đầu tư bất động sản",
    "đầu tư đất",
    "đầu tư căn hộ",
    "đầu tư nhà phố",
    "đầu tư shophouse",
    "đầu tư dòng tiền",
    "sản phẩm đầu tư",
    "tài sản dòng tiền",
    "bất động sản dòng tiền",
    "tìm sản phẩm dòng tiền",
    "tìm tài sản tạo dòng tiền",
    "mua khai thác cho thuê",
    "mua xây căn hộ",
    "mua xây khách sạn",
    "mua làm homestay",
    "mua làm căn hộ dịch vụ",
    "mua đất phân lô",
    "mua đất giữ tài sản",
    "đầu tư dài hạn",
    "đầu tư trung hạn",
    "đón đầu quy hoạch",
    "đón đầu hạ tầng",
    "sinh lời",
    "lợi nhuận",
    "tỷ suất lợi nhuận",
    "roi",
    "cashflow",
    "dòng tiền ổn định",
    "khai thác cho thuê",
    "khả năng tăng giá",
    "tiềm năng tăng giá",
    "giữ tiền",
    "trú ẩn tài sản"
  ],
  tenant: [
    "cần thuê",
    "muốn thuê",
    "đang tìm thuê",
    "tìm thuê",
    "cần tìm thuê",
    "thuê nhà",
    "thuê căn hộ",
    "thuê chung cư",
    "thuê mặt bằng",
    "thuê văn phòng",
    "thuê kho",
    "thuê xưởng",
    "thuê shophouse",
    "thuê nhà nguyên căn",
    "thuê dài hạn",
    "thuê ngắn hạn",
    "tìm mặt bằng kinh doanh",
    "cần mặt bằng kinh doanh",
    "tìm chỗ mở quán",
    "tìm chỗ mở văn phòng",
    "tìm chỗ làm showroom",
    "tìm kho",
    "tìm nhà xưởng",
    "tìm phòng",
    "tìm căn hộ ở",
    "tìm căn hộ gần biển",
    "tìm căn hộ trung tâm",
    "tìm thuê khu nam đà nẵng"
  ],
  renter: [
    'cần thuê',
    'muốn thuê',
    'đang tìm thuê',
    'tìm thuê',
    'thuê nhà',
    'thuê căn',
    'thuê căn hộ',
    'thuê chung cư',
    'thuê mặt bằng',
    'thuê shop',
    'thuê cửa hàng',
    'thuê văn phòng',
    'thuê phòng',
    'ở ghép',
  ],
  seller: [
    "cần bán",
    "muốn bán",
    "đang cần bán",
    "bán gấp",
    "cần bán gấp",
    "chính chủ bán",
    "chính chủ cần bán",
    "gửi bán",
    "nhờ bán",
    "cần ra hàng",
    "ra hàng",
    "ra nhanh",
    "bán nhanh",
    "cần tiền",
    "ngộp tài chính",
    "ngộp ngân hàng",
    "ngộp bank",
    "cắt lỗ",
    "giảm giá bán nhanh",
    "thu hồi vốn",
    "bán đất",
    "bán nhà",
    "bán căn hộ",
    "bán chung cư",
    "bán shophouse",
    "bán biệt thự",
    "bán nhà phố",
    "bán mặt bằng",
    "bán kho",
    "bán xưởng",
    "bán quỹ đất",
    "sang nhượng",
    "cần sang nhượng"
  ],
  landlord: [
    "cho thuê",
    "cần cho thuê",
    "chính chủ cho thuê",
    "cho thuê nhà",
    "cho thuê căn hộ",
    "cho thuê chung cư",
    "cho thuê mặt bằng",
    "cho thuê văn phòng",
    "cho thuê kho",
    "cho thuê xưởng",
    "cho thuê shophouse",
    "cho thuê nhà nguyên căn",
    "cho thuê phòng",
    "cho thuê dài hạn",
    "sang nhượng mặt bằng",
    "sang nhượng cửa hàng"
  ],
  broker: [
    "nhận ký gửi",
    "ký gửi nhà đất",
    "ký gửi bất động sản",
    "môi giới",
    "sale bất động sản",
    "sale bđs",
    "chuyên viên tư vấn",
    "chuyên viên kinh doanh",
    "giỏ hàng",
    "rổ hàng",
    "bảng hàng",
    "hàng độc quyền",
    "hàng chính chủ",
    "hàng mới",
    "nguồn hàng",
    "em có căn",
    "em có lô",
    "bên em có",
    "liên hệ em",
    "ib em",
    "inbox em",
    "hoa hồng",
    "phí môi giới",
    "tuyển sale",
    "tuyển môi giới",
    "tuyển cộng tác viên",
    "cộng tác viên bất động sản"
  ],
  propertyTypes: [
    "đất nền",
    "đất ở",
    "đất thổ cư",
    "đất mặt tiền",
    "đất kiệt",
    "đất hẻm",
    "đất dự án",
    "đất thương mại",
    "đất sản xuất kinh doanh",
    "quỹ đất",
    "lô đất",
    "nhà phố",
    "nhà mặt tiền",
    "nhà kiệt",
    "nhà nguyên căn",
    "biệt thự",
    "shophouse",
    "căn hộ",
    "chung cư",
    "căn hộ dịch vụ",
    "condotel",
    "khách sạn",
    "homestay",
    "mặt bằng",
    "văn phòng",
    "kho",
    "nhà kho",
    "nhà xưởng",
    "xưởng",
    "trọ",
    "dãy trọ",
    "phòng trọ",
    "resort",
    "đất làm dự án"
  ],
  locations: [
    "đà nẵng",
    "nam đà nẵng",
    "hòa xuân",
    "hòa quý",
    "ngũ hành sơn",
    "sơn trà",
    "hải châu",
    "thanh khê",
    "liên chiểu",
    "cẩm lệ",
    "hòa khánh",
    "hòa minh",
    "hòa hiệp",
    "fpt city",
    "fpt",
    "làng đại học",
    "mai đăng chơn",
    "non nước",
    "mỹ khê",
    "võ nguyên giáp",
    "ngô quyền",
    "tôn đức thắng",
    "điện ngọc",
    "điện nam",
    "điện bàn",
    "hội an",
    "cẩm phô",
    "nam hòa xuân",
    "sun cosmo",
    "sun symphony",
    "sơn trà ocean view",
    "cocobay",
    "fpt university",
    "đại học fpt",
    "biển non nước",
    "biển mỹ khê"
  ],
  budgetSignals: [
    "tài chính",
    "ngân sách",
    "tầm tiền",
    "khoảng tiền",
    "vốn",
    "vốn tự có",
    "có sẵn",
    "vay thêm",
    "dưới 2 tỷ",
    "dưới 3 tỷ",
    "dưới 4 tỷ",
    "dưới 5 tỷ",
    "dưới 10 tỷ",
    "trên 10 tỷ",
    "tầm 2 tỷ",
    "tầm 3 tỷ",
    "tầm 4 tỷ",
    "tầm 5 tỷ",
    "tầm 10 tỷ",
    "2 tỷ",
    "3 tỷ",
    "4 tỷ",
    "5 tỷ",
    "6 tỷ",
    "7 tỷ",
    "8 tỷ",
    "10 tỷ",
    "15 tỷ",
    "20 tỷ",
    "30 tỷ",
    "40 tỷ",
    "50 tỷ",
    "triệu",
    "tỷ",
    "thương lượng",
    "thỏa thuận"
  ],
  areaSignals: [
    "diện tích",
    "m2",
    "m²",
    "mét vuông",
    "ngang",
    "dài",
    "mặt tiền",
    "500m2",
    "1000m2",
    "trên 500m2",
    "trên 1000m2",
    "5x20",
    "10x20",
    "15x20",
    "ngang 5m",
    "ngang 10m",
    "ngang 15m"
  ],
  urgencySignals: [
    "cần gấp",
    "mua gấp",
    "thuê gấp",
    "bán gấp",
    "chốt nhanh",
    "chốt trong tuần",
    "chốt trong tháng",
    "xem nhà ngay",
    "xem đất ngay",
    "cần trong hôm nay",
    "cần trong tuần",
    "cần sớm",
    "đang cần",
    "cần ngay",
    "có tiền sẵn",
    "tiền mặt",
    "công chứng nhanh",
    "giao dịch nhanh"
  ],
  propertyRequirements: [
    "đường ô tô",
    "ô tô vào",
    "oto vào",
    "đường lớn",
    "mặt tiền",
    "hai mặt tiền",
    "2 mặt tiền",
    "gần biển",
    "gần trường",
    "gần đại học",
    "gần khu công nghiệp",
    "gần trung tâm",
    "gần fpt",
    "gần làng đại học",
    "gần hội an",
    "sổ đỏ",
    "sổ riêng",
    "pháp lý rõ ràng",
    "pháp lý sạch",
    "đất ở",
    "odt",
    "được xây dựng",
    "xây cao tầng",
    "xây căn hộ",
    "xây khách sạn",
    "kinh doanh được",
    "dòng tiền",
    "đang cho thuê",
    "có sẵn hợp đồng thuê",
    "hướng đông",
    "hướng đông nam",
    "hướng nam",
    "view biển",
    "view sông",
    "view thành phố"
  ],
  exclusionSignals: [
    "tuyển sale bất động sản",
    "tuyển môi giới",
    "tuyển cộng tác viên bất động sản",
    "đào tạo môi giới",
    "khóa học môi giới",
    "chia sẻ nghề môi giới",
    "chạy quảng cáo bất động sản",
    "dịch vụ chạy ads bất động sản",
    "phần mềm đăng tin",
    "phần mềm quét số điện thoại",
    "bán data bất động sản",
    "mua data khách hàng",
    "tuyển dụng nhân sự bất động sản",
    "xe máy",
    "xe ga",
    "mua xe",
    "bán xe máy",
    "bán xe ga",
    "ô tô cũ",
    "oto cũ",
    "bán sim",
    "mua sim",
    "sim số đẹp"
  ]
} as const;

/**
 * Flattened positive pack used when source/mission leave keywords empty.
 * Demand-side only — seller/landlord packs must NOT inflate buyer keywordScore
 * (that was flooding Lead Intelligence with listing posts as "unknown" leads).
 */
export function getDefaultPositiveKeywords(): string[] {
  return unique([
    ...DEFAULT_REAL_ESTATE_KEYWORDS.buyer,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.investor,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.tenant,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.renter,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.propertyTypes,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.locations,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.budgetSignals,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.areaSignals,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.urgencySignals,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.propertyRequirements,
  ]);
}

/** Supply-side pack (seller/landlord/broker listing) — use for supply missions only. */
export function getDefaultSupplyKeywords(): string[] {
  return unique([
    ...DEFAULT_REAL_ESTATE_KEYWORDS.seller,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.landlord,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.broker,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.propertyTypes,
    ...DEFAULT_REAL_ESTATE_KEYWORDS.locations,
  ]);
}

/** Avoidance / exclusion pack (recruiting, ads services, data selling, …). */
export function getDefaultNegativeKeywords(): string[] {
  return unique([...DEFAULT_REAL_ESTATE_KEYWORDS.exclusionSignals]);
}

function unique(items: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of items) {
    const value = item.trim().toLowerCase();
    if (!value || seen.has(value)) continue;
    seen.add(value);
    out.push(value);
  }
  return out;
}
