/** Default CMS categories — seeded once, not hard-coded in public menu */
export const DEFAULT_CMS_CATEGORIES = [
  {
    id: 'cat-tin-thi-truong',
    name: 'Tin thị trường',
    slug: 'tin-thi-truong',
    hubPath: '/tin-tuc/chuyen-muc/tin-thi-truong',
    legacyHubPath: '/tin-thi-truong',
    sortOrder: 1,
    description: 'Cập nhật giá, giao dịch và chính sách mới.',
  },
  {
    id: 'cat-kien-thuc-dau-tu',
    name: 'Kiến thức đầu tư',
    slug: 'kien-thuc-dau-tu',
    hubPath: '/tin-tuc/chuyen-muc/kien-thuc-dau-tu',
    legacyHubPath: '/kien-thuc-dau-tu',
    sortOrder: 2,
    description: 'Hướng dẫn đầu tư BĐS Đà Nẵng từ cơ bản đến nâng cao.',
  },
  {
    id: 'cat-phan-tich-du-an',
    name: 'Phân tích dự án',
    slug: 'phan-tich-du-an',
    hubPath: '/tin-tuc/chuyen-muc/phan-tich-du-an',
    legacyHubPath: '/phan-tich',
    sortOrder: 3,
    description: 'Phân tích dự án và phân khúc BĐS Đà Nẵng.',
  },
  {
    id: 'cat-review-khu-vuc',
    name: 'Review khu vực',
    slug: 'review-khu-vuc',
    hubPath: '/tin-tuc/chuyen-muc/review-khu-vuc',
    legacyHubPath: '/review-khu-vuc',
    sortOrder: 4,
    description: 'Đánh giá tiềm năng từng khu vực Đà Nẵng.',
  },
  {
    id: 'cat-can-ho-sun-group',
    name: 'Căn hộ Sun Group',
    slug: 'can-ho-sun-group',
    hubPath: '/tin-tuc/chuyen-muc/can-ho-sun-group',
    sortOrder: 5,
    description: 'Sun Symphony, Sun Cosmo và hệ sinh thái Sun Group Đà Nẵng.',
  },
  {
    id: 'cat-dat-nen-nha-pho',
    name: 'Đất nền - Nhà phố',
    slug: 'dat-nen-nha-pho',
    hubPath: '/tin-tuc/chuyen-muc/dat-nen-nha-pho',
    sortOrder: 6,
    description: 'Đất nền, nhà phố Nam Đà Nẵng và Mai Đăng Chơn.',
  },
  {
    id: 'cat-phap-ly-bds',
    name: 'Pháp lý BĐS',
    slug: 'phap-ly-bds',
    hubPath: '/tin-tuc/chuyen-muc/phap-ly-bds',
    sortOrder: 7,
    description: 'Sổ hồng, quy hoạch, thủ tục sang tên.',
  },
  {
    id: 'cat-case-study',
    name: 'Case Study',
    slug: 'case-study',
    hubPath: '/tin-tuc/chuyen-muc/case-study',
    sortOrder: 8,
    description: 'Câu chuyện thực tế và bài học đầu tư.',
  },
  {
    id: 'cat-du-lieu-thi-truong',
    name: 'Dữ liệu thị trường',
    slug: 'du-lieu-thi-truong',
    hubPath: '/tin-tuc/chuyen-muc/du-lieu-thi-truong',
    sortOrder: 9,
    description: 'Số liệu, xu hướng và bảng tin thị trường.',
  },
] as const;
